### ISSUE TITLE
build fails on latest gcc version 6.1.1

### ISSUE THREAD

**Issue by neeraj9** [rumpkernel/rumprun#82]
The build fails due to "left shift of negative value" error (see below).

Changes in gcc 6+ which introduced this new error:
- https://gcc.gnu.org/ml/gcc-patches/2015-04/msg01353.html
- https://github.com/gcc-mirror/gcc/commit/cdc64059c5405c2b3c489b071edfe2127cc45333
- https://gcc.gnu.org/gcc-6/changes.html

```
--- dependall-/opt/rumprun/buildrump.sh/brlib ---
In file included from /opt/rumprun/src-netbsd/sys/rump/../sys/stdint.h:35:0,
                 from /opt/rumprun/src-netbsd/sys/rump/../sys/inttypes.h:39,
                 from /opt/rumprun/src-netbsd/sys/rump/../sys/param.h:104,
                 from /opt/rumprun/buildrump.sh/brlib/libnetconfig/netconfig.c:26:
/opt/rumprun/buildrump.sh/brlib/libnetconfig/netconfig.c: In function 'rump_netconfig_ipv4_ifaddr_cidr':
/opt/rumprun/buildrump.sh/brlib/libnetconfig/netconfig.c:235:40: error: left shift of negative value [-Werror=shift-negative-value]
  return cfg_ipv4(ifname, addr, htonl(~0<<(32-mask)));
                                        ^
```

Note: I am building on archlinux (latest).

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.1.1 20160707 (GCC) 
```

**Comment by anttikantee** [comment]
See here:
https://github.com/rumpkernel/buildrump.sh/pull/82

**Comment by gandro** [comment]
I also ran into issues with GCC6 a couple of weeks ago. Unfortunately, I never found the time to investigate them properly. I also ran into this C++ error, which I never managed to fix: https://gist.github.com/gandro/babefd3219a72bf989fed448392a9326

For the other warnings, I was using these patches, but didn't have the time to issue a NetBSD PR and forgot about it. I think some (all?) of them been fixed upstream by now, since they are trivial: https://gist.github.com/gandro/8211fcd5ab4ae231336676f3478870dc

On Arch, you can use the  `community/gcc5` package and use `CC=gcc-5`.

**Comment by anttikantee** [comment]
C++, a neverending adventure.

Apart from the libunwind one, all patches are indeed in upstream now.

You can also build without C++ with `CXX=false ./build-rr.sh ...`

**Comment by neeraj9** [comment]
There is another issue which causes the build to fail again due to another warning added in gcc 6; namely misleading-indentation. The earlier failure in buildrump.sh is fixed by pulling from master (manually).

```
src-netbsd/sys/rump/librump/rumpkern/../../../uvm/uvm_aobj.c:928:5: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
     if (lcv == centeridx ||
     ^~
src-netbsd/sys/rump/librump/rumpkern/../../../uvm/uvm_aobj.c:932:6: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
      continue;
      ^~~~~~~~
```
I could work on some patches but may not be before tonight unless someone fixes them before that. Thanks @gandro  for the suggestion for gcc-5 though I might not take that route :)

**Comment by neeraj9** [comment]
The latest changes to src-netbsd have fixed all the issues barring c++ libunwind code. Thanks @anttikantee 

CXX=false ./build-rr.sh .... now works

**Comment by neeraj9** [comment]
the build with gcc 6.1.x was fixed while this lingered on.
